# Generated by Django 6.0.3 on 2026-03-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_id', models.CharField(db_index=True, max_length=255)),
                ('request_method', models.CharField(max_length=10)),
                ('request_url', models.URLField(max_length=2048)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
