# Generated by Django 6.0.6 on 2026-06-14 00:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint_path', models.CharField(max_length=1024)),
                ('method', models.CharField(max_length=10)),
                ('schema_json', models.JSONField()),
                ('source', models.CharField(blank=True, max_length=50)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_snapshots', to='projects.project')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemaDiff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diff_json', models.JSONField()),
                ('compatibility_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('breaking', models.BooleanField(default=False)),
                ('impact_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_diffs', to='projects.project')),
                ('new_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diffs_as_new', to='contracts.schemasnapshot')),
                ('old_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diffs_as_old', to='contracts.schemasnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
